title: DefiScholar Research
description: Research materials, data, and scripts for defischolar.com
remote_theme: pages-themes/cayman@v0.2.0
google_analytics: # You can add your ID here later if you want to track visitors
